language: node_js
node_js:
  - "6.0"
  - "8.0"
  - "10.0"
sudo: false
after_success:
env:
  - TEST_DIR=client
  - TEST_DIR=server
before_install: if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi
script: cd $TEST_DIR && npm install && npm test